import { StyleSheet } from 'react-native'
import { radiusPixels, semanticColors, spacingPixels } from '@journal/theme'
import {
  textCardHeight,
  textCardHorizontalPadding,
  textCardImageSize,
  textCardVerticalPadding,
  textCarouselItemGap,
} from './photoMapPresentation'

export const photoMapStyles = StyleSheet.create({
  cardNearbyBadge: {
    alignItems: 'center',
    backgroundColor: semanticColors['primary-soft'],
    borderRadius: radiusPixels.full,
    flexShrink: 0,
    justifyContent: 'center',
    maxWidth: 82,
    paddingHorizontal: spacingPixels['1.5'],
    paddingVertical: 1,
  },
  cardNearbyBadgeText: {
    color: semanticColors.primary,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
  },
  cardMetaDate: {
    flexShrink: 0,
  },
  cardDateContent: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: spacingPixels['1'],
    minHeight: 18,
    minWidth: 52,
  },
  cardMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: spacingPixels['1'],
    minHeight: 18,
    minWidth: 0,
  },
  emptyMurmurImage: {
    alignItems: 'center',
    borderColor: semanticColors.border,
    borderWidth: 1,
    gap: spacingPixels['1.5'],
    justifyContent: 'center',
  },
  emptyMurmurIconBubble: {
    alignItems: 'center',
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.border,
    borderRadius: radiusPixels.full,
    borderWidth: 1,
    height: spacingPixels['8'],
    justifyContent: 'center',
    width: spacingPixels['8'],
  },
  emptyMurmurLineLong: {
    backgroundColor: semanticColors.border,
    borderRadius: radiusPixels.full,
    height: 3,
    width: 36,
  },
  emptyMurmurLineShort: {
    backgroundColor: semanticColors.border,
    borderRadius: radiusPixels.full,
    height: 3,
    opacity: 0.72,
    width: 24,
  },
  expandedImageMarker: {
    alignItems: 'center',
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.primary,
    borderRadius: radiusPixels.md,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    shadowColor: semanticColors.foreground,
    shadowOffset: {
      height: 2,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    width: 42,
  },
  expandedImageMarkerImage: {
    backgroundColor: semanticColors['surface-muted'],
    borderRadius: radiusPixels.sm,
    height: 38,
    width: 38,
  },
  expandedTextMarker: {
    backgroundColor: semanticColors.primary,
    borderColor: semanticColors.surface,
    borderRadius: radiusPixels.full,
    borderWidth: 2,
    height: 18,
    shadowColor: semanticColors.foreground,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    width: 18,
  },
  expandedTextMarkerSelected: {
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.primary,
    borderWidth: 3,
    height: 22,
    width: 22,
  },
  imageClusterTray: {
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.border,
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
    bottom: textCardHeight + spacingPixels['6'],
    left: spacingPixels['4'],
    paddingHorizontal: spacingPixels['3'],
    paddingVertical: spacingPixels['2.5'],
    position: 'absolute',
    right: spacingPixels['4'],
    shadowColor: semanticColors.foreground,
    shadowOffset: {
      height: 4,
      width: 0,
    },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    zIndex: 4,
  },
  imageClusterTrayImage: {
    backgroundColor: semanticColors['surface-muted'],
    borderRadius: radiusPixels.md,
    height: 56,
    width: 56,
  },
  imageClusterTrayItem: {
    borderColor: semanticColors.border,
    borderRadius: radiusPixels.md,
    borderWidth: 1,
    height: 58,
    overflow: 'hidden',
    width: 58,
  },
  imageClusterTrayList: {
    gap: spacingPixels['2'],
    paddingTop: spacingPixels['2'],
  },
  mapFrame: {
    backgroundColor: semanticColors['surface-muted'],
    borderColor: semanticColors.border,
    borderRadius: radiusPixels['2xl'],
    borderWidth: 1,
    flex: 1,
    overflow: 'hidden',
  },
  mapImageMarker: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    overflow: 'visible',
    width: 40,
  },
  mapImageMarkerGrouped: {
    height: 46,
    width: 46,
  },
  mapImageMarkerExpanded: {
    opacity: 0.82,
  },
  mapImageMarkerGroupHalo: {
    backgroundColor: semanticColors['primary-soft'],
    borderColor: semanticColors.primary,
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
    bottom: 1,
    left: 1,
    opacity: 0.78,
    position: 'absolute',
    right: 1,
    top: 1,
    transform: [{ rotate: '-7deg' }],
  },
  mapImageMarkerImage: {
    backgroundColor: semanticColors['surface-muted'],
    borderColor: semanticColors.surface,
    borderRadius: radiusPixels.md,
    borderWidth: 1,
    height: 38,
    width: 38,
  },
  mapImageMarkerImageSelected: {
    borderColor: semanticColors.primary,
    borderWidth: 1.5,
  },
  mapImageMarkerSelected: {
    height: 42,
    width: 42,
  },
  mapImageMultiBadge: {
    alignItems: 'center',
    backgroundColor: semanticColors['primary-soft'],
    borderColor: semanticColors.primary,
    borderRadius: radiusPixels.full,
    borderWidth: 1,
    height: 16,
    justifyContent: 'center',
    position: 'absolute',
    right: 1,
    top: 1,
    minWidth: 16,
    paddingHorizontal: 3,
  },
  mapImageMultiBadgeText: {
    color: semanticColors.primary,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 11,
  },
  mapImageNearbyBadge: {
    backgroundColor: semanticColors.primary,
    borderColor: semanticColors.surface,
    height: 18,
    minWidth: 26,
    right: -3,
    top: -3,
  },
  mapImageNearbyBadgeText: {
    color: semanticColors.surface,
    fontSize: 9,
    lineHeight: 11,
  },
  mapTextClusterMarker: {
    height: 30,
    width: 30,
  },
  mapTextClusterMarkerText: {
    color: semanticColors.surface,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
  },
  mapTextMarker: {
    alignItems: 'center',
    backgroundColor: semanticColors.primary,
    borderColor: semanticColors.surface,
    borderRadius: radiusPixels.full,
    borderWidth: 2,
    height: 16,
    justifyContent: 'center',
    shadowColor: semanticColors.foreground,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    width: 16,
  },
  mapTextMarkerExpanded: {
    opacity: 0.74,
  },
  mapTextMarkerSelected: {
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.primary,
    borderWidth: 3,
    height: 22,
    width: 22,
  },
  mapSummary: {
    alignItems: 'center',
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.border,
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacingPixels['3'],
    justifyContent: 'space-between',
    paddingLeft: spacingPixels['3'],
    paddingRight: spacingPixels['3'],
    paddingVertical: spacingPixels['2.5'],
  },
  mapSummaryMain: {
    flex: 1,
    minWidth: 0,
  },
  mapSummaryMetricRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacingPixels['1'],
    marginTop: spacingPixels['1'],
  },
  mapAttribution: {
    bottom: textCardHeight + spacingPixels['5'],
    left: spacingPixels['3'],
    opacity: 0.62,
    position: 'absolute',
    zIndex: 2,
  },
  mapAttributionText: {
    color: semanticColors['text-quaternary'],
    fontSize: 8,
    fontWeight: '500',
    lineHeight: 9,
  },
  mapTopPanel: {
    elevation: 6,
    gap: spacingPixels['2'],
    left: spacingPixels['3'],
    position: 'absolute',
    right: spacingPixels['3'],
    top: spacingPixels['3'],
    zIndex: 2,
  },
  rangeHeaderButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: radiusPixels.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacingPixels['1'],
    height: spacingPixels['8'],
    justifyContent: 'center',
    minWidth: 58,
    paddingHorizontal: spacingPixels['2'],
  },
  rangeHeaderButtonActive: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  rangeMenu: {
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.border,
    borderRadius: radiusPixels.xl,
    borderWidth: 1,
    elevation: 9,
    gap: spacingPixels['1'],
    position: 'absolute',
    right: spacingPixels['4'],
    top: spacingPixels['12'] + spacingPixels['1'],
    padding: spacingPixels['1'],
    shadowColor: semanticColors.foreground,
    shadowOffset: {
      height: 8,
      width: 0,
    },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    zIndex: 8,
  },
  rangeMenuButton: {
    alignItems: 'center',
    borderColor: 'transparent',
    borderRadius: radiusPixels.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: spacingPixels['10'],
    minWidth: 96,
    paddingHorizontal: spacingPixels['3'],
  },
  rangeMenuButtonSelected: {
    backgroundColor: semanticColors['primary-soft'],
    borderColor: semanticColors.primary,
  },
  recenterButton: {
    alignItems: 'center',
    backgroundColor: semanticColors['primary-soft'],
    borderColor: semanticColors.primary,
    borderRadius: radiusPixels.full,
    borderWidth: 1,
    height: spacingPixels['10'],
    justifyContent: 'center',
    width: spacingPixels['10'],
  },
  textCard: {
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.border,
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
    elevation: 1,
    height: textCardHeight,
    overflow: 'hidden',
    shadowColor: semanticColors.foreground,
    shadowOffset: {
      height: 2,
      width: 0,
    },
    shadowOpacity: 0.035,
    shadowRadius: 5,
    width: '100%',
  },
  textCardSelected: {
    borderColor: semanticColors.primary,
    shadowOpacity: 0.05,
  },
  textCardInner: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacingPixels['3.5'],
    minWidth: 0,
    paddingHorizontal: textCardHorizontalPadding,
    paddingVertical: textCardVerticalPadding,
    width: '100%',
  },
  textCardMediaSlot: {
    flexShrink: 0,
    height: textCardImageSize,
    width: textCardImageSize,
  },
  textCardImage: {
    backgroundColor: semanticColors['surface-muted'],
    borderRadius: radiusPixels.md,
    height: textCardImageSize,
    width: textCardImageSize,
  },
  textCardMurmurText: {
    color: semanticColors['text-secondary'],
    flexShrink: 1,
    flexWrap: 'wrap',
    fontSize: 13,
    lineHeight: 18,
    marginTop: spacingPixels['1.5'],
    overflow: 'hidden',
  },
  textCardTextColumn: {
    flex: 1,
    flexShrink: 1,
    height: textCardImageSize,
    justifyContent: 'center',
    minHeight: textCardImageSize,
    minWidth: 0,
    overflow: 'hidden',
  },
  textCarouselList: {
    alignSelf: 'center',
    height: textCardHeight,
    overflow: 'visible',
  },
  textCarouselListContent: {
    alignItems: 'center',
  },
  textCarouselPage: {
    justifyContent: 'center',
    paddingHorizontal: textCarouselItemGap / 2,
    width: '100%',
  },
  textCardTray: {
    bottom: spacingPixels['4'],
    elevation: 0,
    left: 0,
    overflow: 'visible',
    position: 'absolute',
    right: 0,
    width: '100%',
    zIndex: 3,
  },
  statusCard: {
    borderRadius: radiusPixels['2xl'],
    maxWidth: 320,
  },
  overlayHeaderRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    gap: spacingPixels['2'],
    justifyContent: 'space-between',
  },
  overlayMetaText: {
    color: semanticColors['text-tertiary'],
    flexShrink: 0,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
  },
  overlayTitle: {
    color: semanticColors.foreground,
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  textClusterSheet: {
    backgroundColor: semanticColors.surface,
    borderColor: semanticColors.border,
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
    bottom: spacingPixels['4'],
    elevation: 7,
    left: spacingPixels['4'],
    maxHeight: 220,
    paddingHorizontal: spacingPixels['3'],
    paddingVertical: spacingPixels['2.5'],
    position: 'absolute',
    right: spacingPixels['4'],
    shadowColor: semanticColors.foreground,
    shadowOffset: {
      height: 4,
      width: 0,
    },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    zIndex: 5,
  },
  textClusterSheetItem: {
    borderColor: semanticColors.border,
    borderRadius: radiusPixels.md,
    borderWidth: 1,
    paddingHorizontal: spacingPixels['3'],
    paddingVertical: spacingPixels['2'],
  },
  textClusterSheetList: {
    gap: spacingPixels['2'],
    paddingTop: spacingPixels['2'],
  },
  textClusterSheetText: {
    color: semanticColors.foreground,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: spacingPixels['1'],
  },
})
