packages:
  - apps/*
  - packages/*
overrides:
  react: 19.2.3
  react-dom: 19.2.3
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild

patchedDependencies:
  isomorphic-git@1.38.4: patches/isomorphic-git@1.38.4.patch
