export {
  assertSafeRemoteUrl,
  createJournalGitAuthenticatedHttpClient,
  createJournalGitAuthHeaders,
  cloneJournalGitSyncRepository,
  commitJournalChanges,
  getJournalGitSyncStatus,
  initJournalGitSyncRepository,
  pullJournalUpdates,
  pushJournalChanges,
  syncJournalNow,
  type JournalGitCredentials,
  type JournalGitOperationOptions,
  type JournalGitPullResult,
  type JournalGitPushResult,
  type JournalGitRecentCommit,
  type JournalGitRuntime,
  type JournalGitSyncConfig,
  type JournalGitSyncResult,
  type JournalGitSyncStatus,
  type JournalGitTrace,
  type JournalGitTraceDetails,
  type JournalGitTraceEvent,
  type JournalGitTraceValue,
} from './gitCore'
export {
  chooseFallbackMergeContent,
  chooseLastWriteWinsContent,
  createFallbackMergeDriver,
  createLastWriteWinsMergeDriver,
  type FallbackMergeInput,
  type FallbackMergeResult,
  type FallbackMergeSide,
  type LastWriteWinsInput,
  type LastWriteWinsResult,
  type LastWriteWinsSide,
} from './lastWriteWins'
export {
  createJournalMergeDriver,
  createJournalMergeStats,
  mergeTextDiff3,
  type JournalMergeStats,
  type TextMergeInput,
  type TextMergeResult,
} from './smartMerge'
export {
  JournalSyncCoordinator,
  type JournalSyncCoordinatorOptions,
  type SyncOperation,
  type SyncOperationRequest,
  type SyncOperationResult,
  type SyncPendingReason,
  type SyncSnapshot,
  type SyncState,
  type SyncTimerApi,
  type SyncTrigger,
} from './scheduler'
export {
  getJournalSyncStatusPresentation,
  type JournalSyncStatusKind,
  type JournalSyncStatusPresentation,
  type JournalSyncStatusPresentationOptions,
  type JournalSyncStatusTone,
} from './statusPresentation'
